version: '3.8'
services:
  home-hunter:
    container_name: home-hunter
    build: .
    volumes:
      - ./:/app
    environment:
      WEBDRIVER_PATH: /usr/bin/chromedriver
      ENABLE_NOTIFICATIONS: "false"
      NOTIFICATION_URL: ${DISCORD_WEBHOOK_URL}
