version: '3.8'
services:
  home-hunter:
    container_name: home-hunter
    build: .
    volumes:
      - ./:/app
    environment:
      WEBDRIVER_PATH: /usr/bin/chromedriver
      WAIT_SECONDS_BETWEEN_CHECKS: 60 # Every 3 hours
      ENABLE_NOTIFICATIONS: "true"
      NOTIFICATION_URL: ${DISCORD_WEBHOOK_URL}
      DISCORD_ROLE_ID: ${DISCORD_ROLE} # Looks like 123456789012345
      LOG_LEVEL: INFO
    restart: always
